apiVersion: apps/v1
kind: Deployment
metadata:
  name: tenant-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tenant-service
  template:
    metadata:
      labels:
        app: tenant-service
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
      containers:
        - name: tenant-service
          image: vignesh8386/smartpg-tenant-service:v1.0.0
          ports:
            - containerPort: 4001
          envFrom:
            - configMapRef:
                name: smartpg-config
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: smartpg-secrets
                  key: MONGO_URI
                  optional: true
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: smartpg-secrets
                  key: JWT_SECRET
                  optional: true
            - name: PORT
              value: "4001"
          livenessProbe:
            httpGet:
              path: /health
              port: 4001
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ready
              port: 4001
            initialDelaySeconds: 10
            periodSeconds: 5
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "250m"
