apiVersion: v1
kind: Secret
metadata:
  name: smartpg-secrets
  namespace: {{ .Values.namespace | default .Release.Namespace }}
type: Opaque
data:
  MONGO_URI: {{ default "bW9uZ29kYjovL2FkbWluOnBhc3N3b3JkQG1vbmdvZGItc2VydmljZToyNzAxNy8/YXV0aFNvdXJjZT1hZG1pbg==" .Values.secrets.mongoUri | quote }}
  JWT_SECRET: {{ default "c2VjcmV0a2V5" .Values.secrets.jwtSecret | quote }}
  MONGO_USERNAME: {{ default "YWRtaW4=" .Values.secrets.mongoUsername | quote }}
  MONGO_PASSWORD: {{ default "cGFzc3dvcmQ=" .Values.secrets.mongoPassword | quote }}
