apiVersion: v1
kind: Service
metadata:
  name: mongodb-client
  labels:
    app: mongodb
    project: smartpg
spec:
  type: ClusterIP
  selector:
    app: mongodb
  ports:
    - port: 27017
      targetPort: 27017
      name: mongodb
